//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BAMEX.Model
{
    using System;
    using System.Collections.ObjectModel;
    
    public partial class Cargo
    {
        public Nullable<double> Interes { get; set; }
        public Nullable<double> Monto { get; set; }
        public int CargoID { get; set; }
    
        public virtual Movimiento Movimiento { get; set; }
    }
}
