//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BAMEX.Model
{
    using System;
    using System.Collections.ObjectModel;
    
    public partial class Cuenta
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Cuenta()
        {
            this.Movimiento = new ObservableCollection<Movimiento>();
            this.Tarjeta = new ObservableCollection<Tarjeta>();
        }
    
        public Nullable<System.DateTime> Fechacorte { get; set; }
        public Nullable<double> Montoinicial { get; set; }
        public Nullable<double> Saldo { get; set; }
        public int CuentaID { get; set; }
        public string ClienteID { get; set; }
        public string GerenteID { get; set; }
    
        public virtual Cliente Cliente { get; set; }
        public virtual Gerente Gerente { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ObservableCollection<Movimiento> Movimiento { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ObservableCollection<Tarjeta> Tarjeta { get; set; }
    }
}
