//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BAMEX.Model
{
    using System;
    using System.Collections.ObjectModel;
    
    public partial class Movimiento
    {
        public string Concepto { get; set; }
        public Nullable<System.DateTime> Fecha { get; set; }
        public int MovimientoID { get; set; }
        public string CajeroID { get; set; }
        public string CuentaID { get; set; }
    
        public virtual Abono Abono { get; set; }
        public virtual Cajero Cajero { get; set; }
        public virtual Cargo Cargo { get; set; }
        public virtual Cuenta Cuenta { get; set; }
    }
}
