//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BAMEX.Model
{
    using System;
    using System.Collections.ObjectModel;
    
    public partial class Tarjeta
    {
        public Nullable<System.DateTime> Fechaexpiracion { get; set; }
        public string Nombreentarjeta { get; set; }
        public Nullable<int> Numtarjeta { get; set; }
        public Nullable<int> Pincode { get; set; }
        public int TarjetaID { get; set; }
        public int CuentaID { get; set; }
    
        public virtual Cuenta Cuenta { get; set; }
    }
}
